# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

on:
  push:
    branches: [ main ]
    
jobs:

   build:
     runs-on: ubuntu-latest 
  
     steps:

      - name: Cache Docker layers 
        uses: actions/checkout@v2
        with:
          path: /tmp/ .buildx-cache
          keys: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}--buildx-
            
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.sundayjoshua }}
          password: ${{ secrets.simplewhaleci }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.simplewhaleci }}/simplewhale:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
